export const TECH_ICONS = [
  {
    id: 1,
    color: 'bg-blue-500',
    label: 'TS',
    src: '/icons/typescript.svg',
    alt: 'TypeScript',
  },
  {
    id: 2,
    color: 'bg-yellow-400',
    label: 'JS',
    src: '/icons/javascript.svg',
    alt: 'JavaScript',
    height: 22,
    width: 22,
  },
  {
    id: 3,
    color: 'bg-cyan-400',
    label: 'R',
    alt: 'React.js',
    src: '/icons/reactjs.svg',
  },
  {
    id: 4,
    color: 'bg-green-500',
    label: 'Nd',
    alt: 'Node.js',
    src: '/icons/nodejs.svg',
  },
  {
    id: 5,
    color: 'bg-[#0CAA50]',
    label: 'MD',
    src: '/icons/mongodb.svg',
    alt: 'MongoDB',
    height: 15,
    width: 15,
  },
  {
    id: 6,
    color: 'bg-[#38BDF8]',
    label: 'Tw',
    src: '/icons/tailwind.svg',
    alt: 'Tailwind CSS',
  },
  {
    id: 7,
    color: 'bg-[#FFFFFF]',
    label: 'Nx',
    src: '/icons/nextjs.svg',
    alt: 'Next.js',
  },
  {
    id: 8,
    color: 'bg-[#F16529]',
    label: 'HT',
    src: '/icons/html-light.svg',
    alt: 'HTML5',
    height: 22,
    width: 22,
  },
  {
    id: 9,
    color: 'bg-[#2965F1]',
    label: 'CS',
    src: '/icons/css-light.svg',
    alt: 'CSS3',
    height: 22,
    width: 22,
  },
  {
    id: 10,
    color: 'bg-[#FF9902]',
    label: 'AW',
    src: '/icons/aws-light.svg',
    alt: 'AWS',
  },
  {
    id: 11,
    color: 'bg-[#EB4234]',
    label: 'GC',
    src: '/icons/google-cloud-platform.svg',
    alt: 'Google Cloud Platform',
  },
];

export const QUALITIES = [
  { word: 'Developer', color: 'text-theme-orange' },
  { word: 'Dependable' },
  { word: 'Diligent' },
  { word: 'Dreamer' },
  { word: 'Determined' },
  { word: 'Designer', color: 'text-theme-green' },
  { word: 'Devoted' },
  { word: 'Disciplined' },
  { word: 'Detail-Oriented' },
  { word: 'Driven' },
  { word: 'Daring' },
  { word: 'Deliberate' },
  { word: 'Dexterous' },
  { word: 'Dedicated' },
];
